object DependenciesVersionCatalog {
    const val activityComposeVersion = "1.9.0"
    const val androidxTestExtJunitVersion = "1.2.1"
    const val composeBomVersion = "2024.06.00"
    const val coreKtxVersion = "1.13.1"
    const val chuckerVersion = "4.0.0"
    const val desugarJdkLibsVersion = "2.0.4"
    const val espressoCoreVersion = "3.6.1"
    const val hiltVersion = "2.51.1"
    const val hiltNavigationVersion = "1.2.0"
    const val javapoetVersion = "1.13.0"
    const val junitVersion = "4.13.2"
    const val lifecycleRuntimeVersion = "2.8.3"
    const val materialVersion = "1.2.1"
    const val moshiVersion = "1.15.1"
    const val okhttpVersion = "4.12.0"
    const val retrofit2Version = "2.11.0"
    const val timberVersion = "5.0.1"
}